#!/usr/bin/env tsx
/**
 * Generates bundled seed game data for offline / first-run use.
 * Run: npm run sync:seed
 */
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import type { DropSource, EquipmentItem, MonsterStats } from "../src/lib/types";

const empty = {
  stabAttack: 0,
  slashAttack: 0,
  crushAttack: 0,
  magicAttack: 0,
  rangedAttack: 0,
  stabDefence: 0,
  slashDefence: 0,
  crushDefence: 0,
  magicDefence: 0,
  rangedDefence: 0,
  strength: 0,
  rangedStrength: 0,
  magicDamage: 0,
  prayer: 0,
  attackSpeed: 4,
};

function item(
  partial: Omit<EquipmentItem, "bonuses"> & { bonuses: Partial<EquipmentItem["bonuses"]> },
): EquipmentItem {
  return {
    ...partial,
    tradeable: partial.tradeable ?? true,
    bonuses: { ...empty, ...partial.bonuses },
  };
}

const items: EquipmentItem[] = [
  // Weapons
  item({
    id: 4587,
    name: "Dragon scimitar",
    slot: "weapon",
    attackTypes: ["slash"],
    requirements: { attack: 60 },
    gePrice: 59_000,
    bonuses: { slashAttack: 67, strength: 66, attackSpeed: 4 },
  }),
  item({
    id: 4151,
    name: "Abyssal whip",
    slot: "weapon",
    attackTypes: ["slash"],
    requirements: { attack: 70 },
    gePrice: 2_500_000,
    bonuses: { slashAttack: 82, strength: 82, attackSpeed: 4 },
  }),
  item({
    id: 11802,
    name: "Armadyl godsword",
    slot: "weapon",
    twoHanded: true,
    attackTypes: ["slash"],
    requirements: { attack: 75 },
    gePrice: 12_000_000,
    bonuses: { slashAttack: 132, crushAttack: 80, strength: 132, attackSpeed: 6 },
  }),
  item({
    id: 13652,
    name: "Dragon claws",
    slot: "weapon",
    twoHanded: true,
    attackTypes: ["slash"],
    requirements: { attack: 60 },
    gePrice: 65_000_000,
    bonuses: { slashAttack: 45, strength: 44, attackSpeed: 4 },
  }),
  item({
    id: 12006,
    name: "Abyssal tentacle",
    slot: "weapon",
    attackTypes: ["slash"],
    requirements: { attack: 75 },
    gePrice: 850_000,
    bonuses: { slashAttack: 90, strength: 86, attackSpeed: 4 },
  }),
  item({
    id: 13265,
    name: "Abyssal bludgeon",
    slot: "weapon",
    twoHanded: true,
    attackTypes: ["crush"],
    requirements: { attack: 70, strength: 70 },
    gePrice: 12_000_000,
    bonuses: { crushAttack: 102, strength: 85, attackSpeed: 4 },
  }),
  item({
    id: 21003,
    name: "Elder maul",
    slot: "weapon",
    twoHanded: true,
    attackTypes: ["crush"],
    requirements: { attack: 75, strength: 75 },
    gePrice: 80_000_000,
    bonuses: { crushAttack: 135, strength: 147, attackSpeed: 6 },
  }),
  item({
    id: 22325,
    name: "Ghrazi rapier",
    slot: "weapon",
    attackTypes: ["stab"],
    requirements: { attack: 75 },
    gePrice: 90_000_000,
    bonuses: { stabAttack: 94, strength: 89, attackSpeed: 4 },
  }),
  item({
    id: 26219,
    name: "Osmumten's fang",
    slot: "weapon",
    attackTypes: ["stab"],
    requirements: { attack: 82 },
    gePrice: 55_000_000,
    bonuses: { stabAttack: 105, strength: 103, attackSpeed: 5 },
  }),
  item({
    id: 24417,
    name: "Inquisitor's mace",
    slot: "weapon",
    attackTypes: ["crush"],
    requirements: { attack: 80 },
    gePrice: 180_000_000,
    bonuses: { crushAttack: 110, strength: 98, attackSpeed: 4 },
  }),
  item({
    id: 12926,
    name: "Toxic blowpipe",
    slot: "weapon",
    twoHanded: true,
    attackTypes: ["ranged"],
    requirements: { ranged: 75 },
    gePrice: 4_200_000,
    bonuses: { rangedAttack: 30, rangedStrength: 20, attackSpeed: 3 },
  }),
  item({
    id: 20997,
    name: "Twisted bow",
    slot: "weapon",
    twoHanded: true,
    attackTypes: ["ranged"],
    requirements: { ranged: 75 },
    gePrice: 1_400_000_000,
    bonuses: { rangedAttack: 70, attackSpeed: 6 },
  }),
  item({
    id: 11785,
    name: "Armadyl crossbow",
    slot: "weapon",
    attackTypes: ["ranged"],
    requirements: { ranged: 70 },
    gePrice: 28_000_000,
    bonuses: { rangedAttack: 100, attackSpeed: 6 },
  }),
  item({
    id: 26374,
    name: "Zaryte crossbow",
    slot: "weapon",
    attackTypes: ["ranged"],
    requirements: { ranged: 80 },
    gePrice: 280_000_000,
    bonuses: { rangedAttack: 110, attackSpeed: 6 },
  }),
  item({
    id: 25865,
    name: "Bow of faerdhinen",
    slot: "weapon",
    twoHanded: true,
    attackTypes: ["ranged"],
    requirements: { ranged: 80 },
    gePrice: 110_000_000,
    bonuses: { rangedAttack: 128, rangedStrength: 106, attackSpeed: 5 },
  }),
  item({
    id: 21012,
    name: "Dragon hunter lance",
    slot: "weapon",
    attackTypes: ["stab"],
    requirements: { attack: 70 },
    gePrice: 55_000_000,
    bonuses: { stabAttack: 85, strength: 70, attackSpeed: 4 },
  }),
  item({
    id: 11905,
    name: "Trident of the seas",
    slot: "weapon",
    attackTypes: ["magic"],
    requirements: { magic: 75 },
    gePrice: 550_000,
    bonuses: { magicAttack: 15, attackSpeed: 4 },
  }),
  item({
    id: 12899,
    name: "Trident of the swamp",
    slot: "weapon",
    attackTypes: ["magic"],
    requirements: { magic: 75 },
    gePrice: 3_800_000,
    bonuses: { magicAttack: 25, attackSpeed: 4 },
  }),
  item({
    id: 24424,
    name: "Sanguinesti staff",
    slot: "weapon",
    attackTypes: ["magic"],
    requirements: { magic: 75 },
    gePrice: 85_000_000,
    bonuses: { magicAttack: 25, attackSpeed: 4 },
  }),
  item({
    id: 27275,
    name: "Tumeken's shadow",
    slot: "weapon",
    attackTypes: ["magic"],
    requirements: { magic: 85 },
    gePrice: 1_000_000_000,
    bonuses: { magicAttack: 35, magicDamage: 0, attackSpeed: 5 },
  }),
  item({
    id: 1215,
    name: "Dragon dagger",
    slot: "weapon",
    attackTypes: ["stab"],
    requirements: { attack: 60 },
    gePrice: 17_000,
    bonuses: { stabAttack: 40, strength: 40, attackSpeed: 4 },
  }),
  item({
    id: 29555,
    name: "Eclipse atlatl",
    slot: "weapon",
    attackTypes: ["ranged"],
    requirements: { ranged: 50, strength: 50 },
    gePrice: 1_200_000,
    bonuses: { rangedAttack: 50, rangedStrength: 0, strength: 0, attackSpeed: 4 },
  }),

  // Shields / offhand
  item({
    id: 12954,
    name: "Dragon defender",
    slot: "shield",
    tradeable: false,
    bonuses: { stabAttack: 25, slashAttack: 24, crushAttack: 23, strength: 6 },
  }),
  item({
    id: 22322,
    name: "Avernic defender",
    slot: "shield",
    tradeable: false,
    bonuses: { stabAttack: 30, slashAttack: 29, crushAttack: 28, strength: 8 },
  }),
  item({
    id: 21000,
    name: "Twisted buckler",
    slot: "shield",
    gePrice: 12_000_000,
    bonuses: { rangedAttack: 18, rangedDefence: 28 },
  }),
  item({
    id: 12817,
    name: "Elysian spirit shield",
    slot: "shield",
    gePrice: 450_000_000,
    bonuses: {
      stabDefence: 63,
      slashDefence: 65,
      crushDefence: 75,
      magicDefence: 2,
      rangedDefence: 57,
      prayer: 3,
    },
  }),

  // Head
  item({
    id: 10828,
    name: "Helm of neitiznot",
    slot: "head",
    gePrice: 45_000,
    bonuses: { stabDefence: 31, slashDefence: 29, crushDefence: 34, strength: 3, prayer: 3 },
  }),
  item({
    id: 24271,
    name: "Neitiznot faceguard",
    slot: "head",
    gePrice: 18_000_000,
    bonuses: { stabDefence: 59, slashDefence: 60, crushDefence: 62, strength: 8, prayer: 3 },
  }),
  item({
    id: 11826,
    name: "Armadyl helmet",
    slot: "head",
    gePrice: 2_800_000,
    bonuses: { rangedAttack: 10, rangedDefence: 8 },
  }),
  item({
    id: 21018,
    name: "Ancestral hat",
    slot: "head",
    gePrice: 55_000_000,
    bonuses: { magicAttack: 8, magicDamage: 2 },
  }),
  item({
    id: 26382,
    name: "Torva full helm",
    slot: "head",
    gePrice: 180_000_000,
    bonuses: { stabDefence: 59, slashDefence: 60, crushDefence: 62, strength: 8 },
  }),
  item({
    id: 11663,
    name: "Void melee helm",
    slot: "head",
    tradeable: false,
    bonuses: {},
  }),
  item({
    id: 11664,
    name: "Void ranger helm",
    slot: "head",
    tradeable: false,
    bonuses: {},
  }),

  // Capes
  item({
    id: 6570,
    name: "Fire cape",
    slot: "cape",
    tradeable: false,
    bonuses: { stabDefence: 1, slashDefence: 1, crushDefence: 1, strength: 4 },
  }),
  item({
    id: 21295,
    name: "Infernal cape",
    slot: "cape",
    tradeable: false,
    bonuses: { stabDefence: 1, slashDefence: 1, crushDefence: 1, strength: 8 },
  }),
  item({
    id: 22109,
    name: "Ava's assembler",
    slot: "cape",
    tradeable: false,
    bonuses: { rangedAttack: 8, rangedStrength: 2 },
  }),
  item({
    id: 21791,
    name: "Imbued saradomin cape",
    slot: "cape",
    tradeable: false,
    bonuses: { magicAttack: 15, magicDefence: 15 },
  }),

  // Neck
  item({
    id: 1704,
    name: "Amulet of glory",
    slot: "neck",
    gePrice: 12_000,
    bonuses: {
      stabAttack: 10,
      slashAttack: 10,
      crushAttack: 10,
      magicAttack: 10,
      rangedAttack: 10,
      strength: 6,
    },
  }),
  item({
    id: 1725,
    name: "Amulet of strength",
    slot: "neck",
    gePrice: 1_200,
    bonuses: { strength: 10 },
  }),
  item({
    id: 19553,
    name: "Amulet of torture",
    slot: "neck",
    gePrice: 14_000_000,
    bonuses: {
      stabAttack: 15,
      slashAttack: 15,
      crushAttack: 15,
      strength: 10,
    },
  }),
  item({
    id: 19547,
    name: "Necklace of anguish",
    slot: "neck",
    gePrice: 12_000_000,
    bonuses: { rangedAttack: 15, rangedStrength: 5 },
  }),
  item({
    id: 12002,
    name: "Occult necklace",
    slot: "neck",
    gePrice: 850_000,
    bonuses: { magicAttack: 12, magicDamage: 10 },
  }),
  item({
    id: 6585,
    name: "Amulet of fury",
    slot: "neck",
    gePrice: 2_100_000,
    bonuses: {
      stabAttack: 10,
      slashAttack: 10,
      crushAttack: 10,
      magicAttack: 10,
      rangedAttack: 10,
      strength: 8,
      prayer: 5,
    },
  }),

  // Ammo
  item({
    id: 9244,
    name: "Dragon bolts (e)",
    slot: "ammo",
    gePrice: 700,
    bonuses: { rangedStrength: 122 },
  }),
  item({
    id: 21905,
    name: "Diamond bolts (e)",
    slot: "ammo",
    gePrice: 250,
    bonuses: { rangedStrength: 105 },
  }),
  item({
    id: 11212,
    name: "Dragon arrow",
    slot: "ammo",
    gePrice: 900,
    bonuses: { rangedStrength: 60 },
  }),
  item({
    id: 21326,
    name: "Amethyst arrow",
    slot: "ammo",
    gePrice: 180,
    bonuses: { rangedStrength: 55 },
  }),

  // Body
  item({
    id: 10551,
    name: "Fighter torso",
    slot: "body",
    tradeable: false,
    bonuses: { stabDefence: 62, slashDefence: 85, crushDefence: 62, strength: 4 },
  }),
  item({
    id: 11832,
    name: "Bandos chestplate",
    slot: "body",
    gePrice: 18_000_000,
    bonuses: { stabDefence: 98, slashDefence: 93, crushDefence: 105, strength: 4 },
  }),
  item({
    id: 11828,
    name: "Armadyl chestplate",
    slot: "body",
    gePrice: 35_000_000,
    bonuses: { rangedAttack: 33, rangedDefence: 57 },
  }),
  item({
    id: 21021,
    name: "Ancestral robe top",
    slot: "body",
    gePrice: 120_000_000,
    bonuses: { magicAttack: 35, magicDamage: 2 },
  }),
  item({
    id: 26384,
    name: "Torva platebody",
    slot: "body",
    gePrice: 220_000_000,
    bonuses: { stabDefence: 117, slashDefence: 110, crushDefence: 122, strength: 6 },
  }),
  item({
    id: 8839,
    name: "Void knight top",
    slot: "body",
    tradeable: false,
    bonuses: {},
  }),

  // Legs
  item({
    id: 11834,
    name: "Bandos tassets",
    slot: "legs",
    gePrice: 22_000_000,
    bonuses: { stabDefence: 71, slashDefence: 63, crushDefence: 66, strength: 2 },
  }),
  item({
    id: 11830,
    name: "Armadyl chainskirt",
    slot: "legs",
    gePrice: 28_000_000,
    bonuses: { rangedAttack: 20, rangedDefence: 33 },
  }),
  item({
    id: 21024,
    name: "Ancestral robe bottom",
    slot: "legs",
    gePrice: 90_000_000,
    bonuses: { magicAttack: 26, magicDamage: 2 },
  }),
  item({
    id: 21304,
    name: "Obsidian platelegs",
    slot: "legs",
    gePrice: 280_000,
    bonuses: { stabDefence: 46, slashDefence: 43, crushDefence: 41 },
  }),
  item({
    id: 26386,
    name: "Torva platelegs",
    slot: "legs",
    gePrice: 160_000_000,
    bonuses: { stabDefence: 87, slashDefence: 78, crushDefence: 79, strength: 4 },
  }),
  item({
    id: 8840,
    name: "Void knight robe",
    slot: "legs",
    tradeable: false,
    bonuses: {},
  }),

  // Hands
  item({
    id: 7462,
    name: "Barrows gloves",
    slot: "hands",
    tradeable: false,
    bonuses: {
      stabAttack: 12,
      slashAttack: 12,
      crushAttack: 12,
      magicAttack: 6,
      rangedAttack: 12,
      strength: 12,
    },
  }),
  item({
    id: 22981,
    name: "Ferocious gloves",
    slot: "hands",
    gePrice: 7_500_000,
    bonuses: {
      stabAttack: 16,
      slashAttack: 16,
      crushAttack: 16,
      strength: 14,
    },
  }),
  item({
    id: 26235,
    name: "Zaryte vambraces",
    slot: "hands",
    gePrice: 95_000_000,
    bonuses: { rangedAttack: 18, rangedStrength: 2 },
  }),
  item({
    id: 8842,
    name: "Void knight gloves",
    slot: "hands",
    tradeable: false,
    bonuses: {},
  }),

  // Feet
  item({
    id: 3105,
    name: "Climbing boots",
    slot: "feet",
    gePrice: 40_000,
    bonuses: { strength: 2 },
  }),
  item({
    id: 11840,
    name: "Dragon boots",
    slot: "feet",
    gePrice: 80_000,
    bonuses: { strength: 4 },
  }),
  item({
    id: 13239,
    name: "Primordial boots",
    slot: "feet",
    gePrice: 28_000_000,
    bonuses: {
      stabAttack: 2,
      slashAttack: 2,
      crushAttack: 2,
      strength: 5,
    },
  }),
  item({
    id: 13237,
    name: "Pegasian boots",
    slot: "feet",
    gePrice: 35_000_000,
    bonuses: { rangedAttack: 12 },
  }),
  item({
    id: 13235,
    name: "Eternal boots",
    slot: "feet",
    gePrice: 5_500_000,
    bonuses: { magicAttack: 8 },
  }),

  // Rings
  item({
    id: 6737,
    name: "Berserker ring",
    slot: "ring",
    gePrice: 4_500_000,
    bonuses: { strength: 4 },
  }),
  item({
    id: 11773,
    name: "Berserker ring (i)",
    slot: "ring",
    tradeable: false,
    bonuses: { strength: 8 },
  }),
  item({
    id: 11771,
    name: "Archers ring (i)",
    slot: "ring",
    tradeable: false,
    bonuses: { rangedAttack: 8 },
  }),
  item({
    id: 11770,
    name: "Seers ring (i)",
    slot: "ring",
    tradeable: false,
    bonuses: { magicAttack: 8 },
  }),
  item({
    id: 19550,
    name: "Ring of suffering (i)",
    slot: "ring",
    tradeable: false,
    bonuses: {
      stabDefence: 20,
      slashDefence: 20,
      crushDefence: 20,
      magicDefence: 20,
      rangedDefence: 20,
      prayer: 4,
    },
  }),
  item({
    id: 28316,
    name: "Lightbearer",
    slot: "ring",
    gePrice: 18_000_000,
    bonuses: {},
  }),
  item({
    id: 28313,
    name: "Ultor ring",
    slot: "ring",
    gePrice: 95_000_000,
    bonuses: { strength: 12 },
  }),
];

const monsters: MonsterStats[] = [
  {
    id: "abyssal-demon",
    name: "Abyssal demon",
    combatLevel: 124,
    hitpoints: 150,
    attack: 97,
    strength: 67,
    defence: 135,
    magic: 1,
    ranged: 1,
    stabDefence: 20,
    slashDefence: 20,
    crushDefence: 20,
    magicDefence: 0,
    rangedDefence: 20,
    size: 1,
    attributes: ["demon"],
    group: "Slayer",
  },
  {
    id: "gemstone-crab",
    name: "Gemstone Crab",
    combatLevel: 234,
    hitpoints: 1000,
    attack: 1,
    strength: 1,
    defence: 1,
    magic: 1,
    ranged: 1,
    stabDefence: 0,
    slashDefence: 0,
    crushDefence: 0,
    magicDefence: 0,
    rangedDefence: 0,
    size: 3,
    group: "Bosses",
  },
  {
    id: "general-graardor",
    name: "General Graardor",
    combatLevel: 624,
    hitpoints: 255,
    attack: 280,
    strength: 350,
    defence: 250,
    magic: 80,
    ranged: 350,
    stabDefence: 90,
    slashDefence: 90,
    crushDefence: 90,
    magicDefence: 200,
    rangedDefence: 90,
    size: 3,
    attributes: ["goblin"],
    group: "God Wars",
  },
  {
    id: "kreearra",
    name: "Kree'arra",
    combatLevel: 580,
    hitpoints: 255,
    attack: 300,
    strength: 200,
    defence: 260,
    magic: 200,
    ranged: 300,
    stabDefence: 120,
    slashDefence: 120,
    crushDefence: 120,
    magicDefence: 160,
    rangedDefence: 100,
    size: 3,
    attributes: ["avian"],
    group: "God Wars",
  },
  {
    id: "commander-zilyana",
    name: "Commander Zilyana",
    combatLevel: 596,
    hitpoints: 255,
    attack: 225,
    strength: 228,
    defence: 200,
    magic: 300,
    ranged: 225,
    stabDefence: 100,
    slashDefence: 100,
    crushDefence: 100,
    magicDefence: 100,
    rangedDefence: 100,
    size: 2,
    group: "God Wars",
  },
  {
    id: "kril-tsutsaroth",
    name: "K'ril Tsutsaroth",
    combatLevel: 650,
    hitpoints: 255,
    attack: 340,
    strength: 300,
    defence: 270,
    magic: 200,
    ranged: 1,
    stabDefence: 80,
    slashDefence: 80,
    crushDefence: 80,
    magicDefence: 130,
    rangedDefence: 80,
    size: 3,
    attributes: ["demon"],
    group: "God Wars",
  },
  {
    id: "zulrah",
    name: "Zulrah",
    combatLevel: 725,
    hitpoints: 500,
    attack: 1,
    strength: 1,
    defence: 300,
    magic: 300,
    ranged: 300,
    stabDefence: 0,
    slashDefence: 0,
    crushDefence: 0,
    magicDefence: 0,
    rangedDefence: 0,
    size: 5,
    group: "Bosses",
  },
  {
    id: "vorkath",
    name: "Vorkath",
    combatLevel: 732,
    hitpoints: 750,
    attack: 560,
    strength: 308,
    defence: 214,
    magic: 150,
    ranged: 308,
    stabDefence: 26,
    slashDefence: 76,
    crushDefence: 126,
    magicDefence: 240,
    rangedDefence: 26,
    size: 7,
    attributes: ["dragon", "draconic"],
    group: "Bosses",
  },
  {
    id: "phantom-muspah",
    name: "Phantom Muspah",
    combatLevel: 741,
    hitpoints: 850,
    attack: 200,
    strength: 200,
    defence: 200,
    magic: 200,
    ranged: 200,
    stabDefence: 80,
    slashDefence: 80,
    crushDefence: 80,
    magicDefence: 80,
    rangedDefence: 80,
    size: 5,
    group: "Bosses",
  },
  {
    id: "vardorvis",
    name: "Vardorvis",
    combatLevel: 784,
    hitpoints: 700,
    attack: 280,
    strength: 280,
    defence: 215,
    magic: 1,
    ranged: 1,
    stabDefence: 215,
    slashDefence: 215,
    crushDefence: 80,
    magicDefence: 60,
    rangedDefence: 215,
    size: 2,
    group: "Desert Treasure II",
  },
  {
    id: "duke-sucellus",
    name: "Duke Sucellus",
    combatLevel: 758,
    hitpoints: 440,
    attack: 300,
    strength: 250,
    defence: 250,
    magic: 250,
    ranged: 1,
    stabDefence: 100,
    slashDefence: 100,
    crushDefence: 100,
    magicDefence: 60,
    rangedDefence: 160,
    size: 5,
    attributes: ["demon"],
    group: "Desert Treasure II",
  },
  {
    id: "the-whisperer",
    name: "The Whisperer",
    combatLevel: 791,
    hitpoints: 900,
    attack: 1,
    strength: 1,
    defence: 150,
    magic: 280,
    ranged: 280,
    stabDefence: 50,
    slashDefence: 50,
    crushDefence: 50,
    magicDefence: 100,
    rangedDefence: 100,
    size: 3,
    group: "Desert Treasure II",
  },
  {
    id: "the-leviathan",
    name: "The Leviathan",
    combatLevel: 798,
    hitpoints: 900,
    attack: 1,
    strength: 1,
    defence: 200,
    magic: 160,
    ranged: 300,
    stabDefence: 80,
    slashDefence: 80,
    crushDefence: 80,
    magicDefence: 160,
    rangedDefence: 60,
    size: 7,
    group: "Desert Treasure II",
  },
  {
    id: "baba",
    name: "Ba-Ba",
    combatLevel: 359,
    hitpoints: 380,
    attack: 150,
    strength: 150,
    defence: 100,
    magic: 80,
    ranged: 80,
    stabDefence: 60,
    slashDefence: 80,
    crushDefence: 40,
    magicDefence: 80,
    rangedDefence: 60,
    size: 5,
    group: "Tombs of Amascut",
  },
  {
    id: "zebak",
    name: "Zebak",
    combatLevel: 371,
    hitpoints: 580,
    attack: 1,
    strength: 1,
    defence: 100,
    magic: 100,
    ranged: 150,
    stabDefence: 50,
    slashDefence: 50,
    crushDefence: 50,
    magicDefence: 80,
    rangedDefence: 40,
    size: 5,
    group: "Tombs of Amascut",
  },
  {
    id: "kephri",
    name: "Kephri",
    combatLevel: 341,
    hitpoints: 200,
    attack: 1,
    strength: 1,
    defence: 80,
    magic: 100,
    ranged: 1,
    stabDefence: 40,
    slashDefence: 40,
    crushDefence: 40,
    magicDefence: 40,
    rangedDefence: 100,
    size: 5,
    group: "Tombs of Amascut",
  },
  {
    id: "akkha",
    name: "Akkha",
    combatLevel: 340,
    hitpoints: 400,
    attack: 140,
    strength: 140,
    defence: 80,
    magic: 140,
    ranged: 140,
    stabDefence: 60,
    slashDefence: 60,
    crushDefence: 60,
    magicDefence: 60,
    rangedDefence: 60,
    size: 3,
    group: "Tombs of Amascut",
  },
  {
    id: "verzik-p2",
    name: "Verzik Vitur (Phase 2)",
    combatLevel: 1520,
    hitpoints: 3250,
    attack: 400,
    strength: 400,
    defence: 200,
    magic: 400,
    ranged: 400,
    stabDefence: 100,
    slashDefence: 100,
    crushDefence: 100,
    magicDefence: 70,
    rangedDefence: 100,
    size: 5,
    group: "Theatre of Blood",
  },
  {
    id: "great-olm",
    name: "Great Olm",
    combatLevel: 1043,
    hitpoints: 800,
    attack: 250,
    strength: 250,
    defence: 250,
    magic: 250,
    ranged: 250,
    stabDefence: 200,
    slashDefence: 200,
    crushDefence: 200,
    magicDefence: 50,
    rangedDefence: 200,
    size: 5,
    group: "Chambers of Xeric",
  },
  {
    id: "corporeal-beast",
    name: "Corporeal Beast",
    combatLevel: 785,
    hitpoints: 2000,
    attack: 320,
    strength: 320,
    defence: 310,
    magic: 350,
    ranged: 1,
    stabDefence: 25,
    slashDefence: 200,
    crushDefence: 100,
    magicDefence: 75,
    rangedDefence: 230,
    size: 5,
    group: "Bosses",
  },
  {
    id: "king-black-dragon",
    name: "King Black Dragon",
    combatLevel: 276,
    hitpoints: 240,
    attack: 240,
    strength: 240,
    defence: 240,
    magic: 240,
    ranged: 1,
    stabDefence: 70,
    slashDefence: 70,
    crushDefence: 70,
    magicDefence: 50,
    rangedDefence: 50,
    size: 5,
    attributes: ["dragon", "draconic"],
    group: "Bosses",
  },
  {
    id: "kalphite-queen",
    name: "Kalphite Queen",
    combatLevel: 333,
    hitpoints: 255,
    attack: 300,
    strength: 300,
    defence: 300,
    magic: 150,
    ranged: 1,
    stabDefence: 50,
    slashDefence: 50,
    crushDefence: 10,
    magicDefence: 100,
    rangedDefence: 100,
    size: 5,
    group: "Bosses",
  },
  {
    id: "tormented-demon",
    name: "Tormented Demon",
    combatLevel: 450,
    hitpoints: 600,
    attack: 200,
    strength: 200,
    defence: 200,
    magic: 200,
    ranged: 200,
    stabDefence: 80,
    slashDefence: 80,
    crushDefence: 80,
    magicDefence: 80,
    rangedDefence: 80,
    size: 3,
    attributes: ["demon"],
    group: "Slayer",
  },
  {
    id: "jal-zeb",
    name: "Jal-Zek",
    combatLevel: 490,
    hitpoints: 220,
    attack: 250,
    strength: 250,
    defence: 150,
    magic: 200,
    ranged: 1,
    stabDefence: 50,
    slashDefence: 50,
    crushDefence: 50,
    magicDefence: 50,
    rangedDefence: 80,
    size: 4,
    group: "Inferno",
  },
  {
    id: "tzkal-zuk",
    name: "TzKal-Zuk",
    combatLevel: 1400,
    hitpoints: 1200,
    attack: 350,
    strength: 350,
    defence: 150,
    magic: 150,
    ranged: 350,
    stabDefence: 0,
    slashDefence: 0,
    crushDefence: 0,
    magicDefence: 0,
    rangedDefence: 0,
    size: 7,
    group: "Inferno",
  },
];

const drops: DropSource[] = [
  { itemId: 4151, itemName: "Abyssal whip", monsterId: "abyssal-demon", monsterName: "Abyssal demon", rarity: 512, quantityMin: 1, quantityMax: 1, combatLevel: 124 },
  { itemId: 11802, itemName: "Armadyl godsword", monsterId: "general-graardor", monsterName: "General Graardor", rarity: 508, quantityMin: 1, quantityMax: 1, combatLevel: 624 },
  { itemId: 11832, itemName: "Bandos chestplate", monsterId: "general-graardor", monsterName: "General Graardor", rarity: 381, quantityMin: 1, quantityMax: 1, combatLevel: 624 },
  { itemId: 11834, itemName: "Bandos tassets", monsterId: "general-graardor", monsterName: "General Graardor", rarity: 381, quantityMin: 1, quantityMax: 1, combatLevel: 624 },
  { itemId: 11826, itemName: "Armadyl helmet", monsterId: "kreearra", monsterName: "Kree'arra", rarity: 381, quantityMin: 1, quantityMax: 1, combatLevel: 580 },
  { itemId: 11828, itemName: "Armadyl chestplate", monsterId: "kreearra", monsterName: "Kree'arra", rarity: 381, quantityMin: 1, quantityMax: 1, combatLevel: 580 },
  { itemId: 11830, itemName: "Armadyl chainskirt", monsterId: "kreearra", monsterName: "Kree'arra", rarity: 381, quantityMin: 1, quantityMax: 1, combatLevel: 580 },
  { itemId: 11785, itemName: "Armadyl crossbow", monsterId: "commander-zilyana", monsterName: "Commander Zilyana", rarity: 508, quantityMin: 1, quantityMax: 1, combatLevel: 596 },
  { itemId: 12002, itemName: "Occult necklace", monsterId: "kril-tsutsaroth", monsterName: "K'ril Tsutsaroth", rarity: 512, quantityMin: 1, quantityMax: 1, combatLevel: 650 },
  { itemId: 12926, itemName: "Toxic blowpipe", monsterId: "zulrah", monsterName: "Zulrah", rarity: 512, quantityMin: 1, quantityMax: 1, combatLevel: 725 },
  { itemId: 12927, itemName: "Serpentine visage", monsterId: "zulrah", monsterName: "Zulrah", rarity: 1024, quantityMin: 1, quantityMax: 1, combatLevel: 725 },
  { itemId: 22106, itemName: "Dragon hunter lance", monsterId: "vorkath", monsterName: "Vorkath", rarity: 1500, quantityMin: 1, quantityMax: 1, combatLevel: 732 },
  { itemId: 22325, itemName: "Ghrazi rapier", monsterId: "verzik-p2", monsterName: "Verzik Vitur", rarity: 650, quantityMin: 1, quantityMax: 1, combatLevel: 1520 },
  { itemId: 22322, itemName: "Avernic defender hilt", monsterId: "verzik-p2", monsterName: "Verzik Vitur", rarity: 550, quantityMin: 1, quantityMax: 1, combatLevel: 1520 },
  { itemId: 21003, itemName: "Elder maul", monsterId: "great-olm", monsterName: "Great Olm", rarity: 500, quantityMin: 1, quantityMax: 1, combatLevel: 1043 },
  { itemId: 21018, itemName: "Ancestral hat", monsterId: "great-olm", monsterName: "Great Olm", rarity: 341, quantityMin: 1, quantityMax: 1, combatLevel: 1043 },
  { itemId: 21021, itemName: "Ancestral robe top", monsterId: "great-olm", monsterName: "Great Olm", rarity: 341, quantityMin: 1, quantityMax: 1, combatLevel: 1043 },
  { itemId: 21024, itemName: "Ancestral robe bottom", monsterId: "great-olm", monsterName: "Great Olm", rarity: 341, quantityMin: 1, quantityMax: 1, combatLevel: 1043 },
  { itemId: 20997, itemName: "Twisted bow", monsterId: "great-olm", monsterName: "Great Olm", rarity: 692, quantityMin: 1, quantityMax: 1, combatLevel: 1043 },
  { itemId: 12817, itemName: "Elysian spirit shield", monsterId: "corporeal-beast", monsterName: "Corporeal Beast", rarity: 4000, quantityMin: 1, quantityMax: 1, combatLevel: 785 },
  { itemId: 13265, itemName: "Abyssal bludgeon", monsterId: "abyssal-demon", monsterName: "Abyssal demon (sire)", rarity: 100, quantityMin: 1, quantityMax: 1, combatLevel: 350 },
  { itemId: 19553, itemName: "Amulet of torture", monsterId: "tortured-gorilla", monsterName: "Tortured gorilla", rarity: 1500, quantityMin: 1, quantityMax: 1, combatLevel: 141 },
  { itemId: 19547, itemName: "Necklace of anguish", monsterId: "demonic-gorilla", monsterName: "Demonic gorilla", rarity: 1500, quantityMin: 1, quantityMax: 1, combatLevel: 275 },
  { itemId: 26219, itemName: "Osmumten's fang", monsterId: "baba", monsterName: "Tombs of Amascut", rarity: 50, quantityMin: 1, quantityMax: 1, combatLevel: 359 },
  { itemId: 27275, itemName: "Tumeken's shadow", monsterId: "akkha", monsterName: "Tombs of Amascut", rarity: 86, quantityMin: 1, quantityMax: 1, combatLevel: 340 },
  { itemId: 26374, itemName: "Zaryte crossbow", monsterId: "phantom-muspah", monsterName: "Phantom Muspah", rarity: 250, quantityMin: 1, quantityMax: 1, combatLevel: 741 },
  { itemId: 26382, itemName: "Torva full helm", monsterId: "nex", monsterName: "Nex", rarity: 258, quantityMin: 1, quantityMax: 1, combatLevel: 1001 },
  { itemId: 28313, itemName: "Ultor ring", monsterId: "vardorvis", monsterName: "Vardorvis", rarity: 720, quantityMin: 1, quantityMax: 1, combatLevel: 784 },
  { itemId: 28316, itemName: "Lightbearer", monsterId: "the-whisperer", monsterName: "The Whisperer", rarity: 720, quantityMin: 1, quantityMax: 1, combatLevel: 791 },
  { itemId: 22981, itemName: "Ferocious gloves", monsterId: "hydra", monsterName: "Alchemical Hydra", rarity: 362, quantityMin: 1, quantityMax: 1, combatLevel: 426 },
  { itemId: 13239, itemName: "Primordial boots", monsterId: "cerberus", monsterName: "Cerberus", rarity: 512, quantityMin: 1, quantityMax: 1, combatLevel: 318 },
  { itemId: 13237, itemName: "Pegasian boots", monsterId: "cerberus", monsterName: "Cerberus", rarity: 512, quantityMin: 1, quantityMax: 1, combatLevel: 318 },
  { itemId: 13235, itemName: "Eternal boots", monsterId: "cerberus", monsterName: "Cerberus", rarity: 512, quantityMin: 1, quantityMax: 1, combatLevel: 318 },
  { itemId: 13652, itemName: "Dragon claws", monsterId: "great-olm", monsterName: "Chambers of Xeric", rarity: 341, quantityMin: 1, quantityMax: 1, combatLevel: 1043 },
  { itemId: 24424, itemName: "Sanguinesti staff", monsterId: "verzik-p2", monsterName: "Theatre of Blood", rarity: 650, quantityMin: 1, quantityMax: 1, combatLevel: 1520 },
  { itemId: 25865, itemName: "Bow of faerdhinen", monsterId: "hunllef", monsterName: "Corrupted Hunllef", rarity: 50, quantityMin: 1, quantityMax: 1, combatLevel: 291 },
  { itemId: 29555, itemName: "Eclipse atlatl", monsterId: "eclipse-moon", monsterName: "Eclipse Moon", rarity: 56, quantityMin: 1, quantityMax: 1, combatLevel: 329 },
];

const outDir = join(process.cwd(), "data");
mkdirSync(outDir, { recursive: true });
mkdirSync(join(process.cwd(), "src/lib/data"), { recursive: true });

const payload = {
  version: 1,
  generatedAt: new Date().toISOString(),
  items,
  monsters,
  drops,
};

writeFileSync(join(outDir, "game-data.json"), JSON.stringify(payload, null, 2));
writeFileSync(
  join(process.cwd(), "src/lib/data/game-data.json"),
  JSON.stringify(payload, null, 2),
);

console.log(
  `Wrote ${items.length} items, ${monsters.length} monsters, ${drops.length} drops.`,
);
